    <li class="ui-menu-item level0 classic parent ">
        <div class="open-children-toggle">&nbsp;</div>
        <a class="level-top"> Pages </a>
        <div class="level0 submenu">
            <div class="row">
                <ul class="subchildmenu ">
                    <li class="ui-menu-item level1 "><a href="{{store url='rokanthemes-brand.html'}}"> Brands </a></li>
                    <li class="ui-menu-item level1 "><a href="{{store url='about-us'}}"> About Us </a></li>
                    <li class="ui-menu-item level1 "><a href="{{store url='privacy-policy-cookie-restriction-mode'}}"> Privacy Policy </a></li>
                </ul>
            </div>
        </div>
    </li>
    <li class="ui-menu-item level0"><a class="level-top" href="{{store url='blog'}}">Blog</a></li>
    <li class="ui-menu-item level0"><a class="level-top" href="{{store url='contact'}}">Contact Us</a></li>
